package et.guzo.domain.enums;

public enum PackageStatus {
    CREATED, AT_ORIGIN, AT_BRANCH, IN_WAREHOUSE, SORTED, DISPATCHED, IN_TRANSIT,
    OUT_FOR_DELIVERY, READY_FOR_PICKUP, DELIVERED, LOST, DAMAGED, RETURNED
}
