package et.guzo.domain.enums;

public enum TrackingEventType {
    ORDER_CREATED, PAYMENT_CONFIRMED, DRIVER_ASSIGNED, PICKED_UP, ARRIVED_AT_BRANCH, ARRIVED_AT_WAREHOUSE,
    SORTED, DISPATCHED, IN_TRANSIT, OUT_FOR_DELIVERY, DELIVERY_ATTEMPTED, DELIVERED,
    CANCELLED, RETURNED, EXCEPTION
}
