spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/Guzo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}

guzo:
  jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
